# Generated by Django 2.2 on 2021-01-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('prsn_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=12)),
                ('country', models.CharField(default='usa', max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Category')),
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trns_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('prsn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Person')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TransCategory',
            fields=[
                ('trns_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='businessops_api.Transaction')),
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['exp_id'],
            },
            bases=('businessops_api.transaction',),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='businessops_api.Transaction')),
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['rev_id'],
            },
            bases=('businessops_api.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trns_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.TransCategory'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('healing_property', models.TextField(default='none')),
                ('description', models.TextField(default='none')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='products')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Category')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='none')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('unit_measure', models.CharField(default='count', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='businessops_api.Person')),
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('hr_rt', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(max_length=25)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessops_api.Department')),
            ],
            options={
                'ordering': ['emp_id'],
            },
            bases=('businessops_api.person',),
        ),
    ]
